//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RegExp.rc
//
#define IDR_MAINFRAME                   100
#define IDS_APP_TITLE                   101
#define ID_HIDE_EMPTY                   102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_REGEXP                      107
#define IDI_FOLDER                      108
#define IDI_COMPUTER                    109
#define IDI_FOLDER_CLOSED               110
#define IDI_FOLDER_ACCESSDENIED         111
#define IDI_HIVE                        112
#define IDI_HIVE_ACCESSDENIED           113
#define IDI_REAL_REG                    114
#define IDI_LOCK                        115
#define IDI_COPY                        128
#define IDI_CUT                         129
#define IDI_PASTE                       130
#define IDI_UNDO                        131
#define IDI_REDO                        132
#define IDI_FIND                        133
#define IDI_QUICKFIND                   134
#define IDI_FOLDER_LINK                 135
#define IDI_REFRESH                     136
#define IDR_CONTEXT                     137
#define IDI_DELETE                      138
#define IDI_BACK                        139
#define IDI_FORWARD                     140
#define IDI_FOLDER_UP                   141
#define IDI_BINARY                      142
#define IDI_TEXT                        143
#define IDI_FOLDER_NEW                  144
#define IDI_RENAME                      145
#define IDI_FOLDER_VIEW                 146
#define IDI_FIND_NEXT                   147
#define IDI_FINDALL                     148
#define IDI_NUM4                        149
#define IDI_NUM8                        150
#define IDI_PERM                        151
#define IDI_EXPORT                      152
#define IDI_PROPERTIES                  153
#define IDI_IMPORT                      154
#define IDI_NUM1                        155
#define IDI_NUM2                        156
#define IDI_NUM8_2                      157
#define IDI_OPTIONS                     158
#define IDI_FOLDER_LOAD                 159
#define IDD_FIND                        160
#define IDD_FINDALL                     161
#define IDD_STRINGVALUE                 162
#define IDD_MULTISTRVALUE               163
#define IDD_NUMBERVALUE                 164
#define IDD_BINVALUE                    165
#define IDD_EXPORT                      166
#define IDD_LOADHIVE                    167
#define IDD_GOTOKEY                     168
#define IDI_GOTO                        169
#define IDD_TEST                        170
#define IDI_ICON1                       171
#define IDI_CHECK                       171
#define IDI_REGREMOTE                   172
#define IDD_CONNECTREG                  173
#define IDD_HANDLES                     174
#define IDC_TEXT                        1000
#define IDC_FIND                        1001
#define IDC_SEARCH_KEYS                 1002
#define IDC_SEARCH_VALUES               1003
#define IDC_SEARCH_DATA                 1004
#define IDC_SEARCH_ALL                  1005
#define IDC_SEARCH_STD                  1006
#define IDC_SEARCH_REAL                 1007
#define IDC_SEARCH_SELECTED             1008
#define IDC_SEARCH_CASE                 1009
#define IDC_SEARCH_MATCHWHOLE           1010
#define IDC_PROGRESS                    1011
#define IDC_CANCEL                      1012
#define IDC_NEW                         1014
#define IDC_STATUS                      1015
#define IDC_VERSION                     1016
#define IDC_COPYRIGHT                   1017
#define IDC_LIST                        1018
#define IDC_APPEND                      1019
#define IDC_SAVE                        1020
#define IDC_LOAD                        1021
#define IDC_PROGRESS1                   1022
#define IDC_NAME                        1023
#define IDC_VALUE                       1024
#define IDC_STRING                      1025
#define IDC_EXPANDSTRING                1026
#define IDC_FILE                        1028
#define IDC_BUTTON3                     1029
#define IDC_FOLDER                      1029
#define IDC_DECIMAL                     1030
#define IDC_HEX                         1031
#define IDC_BINARY                      1032
#define IDC_BUTTON1                     1033
#define IDC_COLOR                       1033
#define IDC_BUFFERSIZE                  1035
#define IDC_EXPORT_STD                  1036
#define IDC_EXPORT_REAL                 1037
#define IDC_RADIO3                      1038
#define IDC_EXPORTKEY                   1038
#define IDC_KEY                         1039
#define IDC_PATH                        1040
#define IDC_BROWSE                      1041
#define IDC_MACHINE                     1042
#define IDC_USERS                       1043
#define IDC_LINK                        1045
#define IDC_HANDLECOUNT                 1050
#define ID_FILE_RUNASADMIN              32771
#define ID_OPTIONS_ALWAYSONTOP          32772
#define ID_VIEW_GOBACK                  32779
#define ID_VIEW_GOFORWARD               32780
#define ID_VIEW_SHOWKEYSINLIST          32781
#define ID_OPTIONS_TREEFONT             32782
#define ID_OPTIONS_LISTFONT             32783
#define ID_OPTIONS_COLORS               32784
#define ID_VIEW_TOOLBAR32785            32785
#define ID_VIEW_STATUSBAR               32786
#define ID_SEARCH_FIND                  32788
#define ID_SEARCH_QUICKFIND             32789
#define ID_KEY_NEW                      32790
#define ID_EDIT_READONLY                32791
#define ID_OPTIONS_SHOWEXTRAHIVES       32792
#define ID_KEY_PROPERTIES               32793
#define ID_NEW_KEY                      32794
#define ID_NEW_DWORDVALUE               32795
#define ID_NEW_QWORDVALUE               32796
#define ID_NEW_STRINGVALUE              32797
#define ID_NEW_MULTIPLESTRINGSVALUE     32798
#define ID_NEW_EXPANDSTRINGVALUE        32799
#define ID_NEW_BINARYVALUE              32800
#define ID_KEY_PERMISSIONS              32801
#define ID_TREE_COPYKEYNAME             32802
#define ID_TREE_COPYFULLKEYNAME         32803
#define ID_FILE_EXPORT                  32804
#define ID_FILE_LOADHIVE                32805
#define ID_TREE                         32806
#define ID_EDIT_RENAME                  32807
#define ID_SEARCH_FINDNEXT              32813
#define ID_TREE_REFRESH                 32814
#define ID_COPY_FULLNAME                32815
#define ID_COPY_NAME                    32816
#define ID_LOCATIONS_SERVICES           32817
#define ID_LOCATIONS_HARDWARE           32818
#define ID_LOCATIONS_CLASS              32819
#define ID_LOCATIONS_HIVELIST           32820
#define ID_LOCATIONS_IMAGEFILEEXECUTIONOPTIONS 32821
#define ID_OPTIONS_UNDO                 32841
#define ID_OPTIONS_UNDOREDO             32842
#define ID_SEARCH_FINDALL               32843
#define ID_FILE_IMPORT                  32844
#define ID_HEX_8BYTES                   32846
#define ID_HEX_16BYTES                  32847
#define ID_HEX_24BYTES                  32848
#define ID_HEX_32BYTES                  32849
#define ID_OPTIONS_REPLACEREGEDIT       32850
#define ID_OPTIONS_DARKMODE             32852
#define ID_OPTIONS_ALLOWSINGLEINSTANCE  32853
#define ID_FILE_UNLOADHIVE              32854
#define ID_KEY_GOTO                     32857
#define ID_HELP_TEST                    32859
#define ID_VIEW_ADDRESSBAR              32860
#define ID_EDIT_ADDRESSBAR              32861
#define ID_BOOKMARKS_BOOKMARKS          32864
#define ID_FILE_CONNECTREMOTEREGISTRY   32865
#define ID_FILE_DISCONNECT              32866
#define ID_LOCATIONS_MANAGE             32867
#define ID_OPTIONS_FONT                 32868
#define ID_OPTIONS_RESTOREDEFAULTFONT   32869
#define ID_TOOLS_SCANKEYHANDLES         32870
#define ID_HANDLES_CLOSEHANDLES         32871
#define ID_EDIT_COPY2                   32872
#define ID_KEY_PERMISSIONS2             32873

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32874
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
